name: BetterBedTime
version: 1.0-SNAPSHOT
main: me.deadspark.plugin.betterbedtime.BetterBedTime
authors: [DeadSpark]
description: A Plugin adding more features to a bed
website: https://deadspark.github.io/MysticalCrafts/
commands:
  bbt:
    description: Information about plugin.