name: BetterBedTime
version: ${project.version}
main: me.deadspark.plugin.betterbedtime.BetterBedTime
api-version: spigot-1.15.2
authors: [DeadSpark]
description: Adds more features to default minecraft bed!
website: https://deadspark.github.io/MysticalCrafts/
commands:
  bbt:
    description: Information about plugin.
